name: tba_api_client
version: 
description: (Unofficial) client library for the TheBlueAlliance.com API
authors:
  - Eric Fletcher <tba-api@thefletcher.net>
homepage: https://github.com/TBA-API/tba-api-client-dart
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  http: '>=0.12.0 <0.13.0'
dev_dependencies:
  test: ^1.3.0
